"""Add description to MeetingRoom

Revision ID: fb9ee535734e
Revises: a2827d309f67
Create Date: 2025-01-24 12:41:27.765351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb9ee535734e'
down_revision = 'a2827d309f67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting_rooms', sa.Column('description', sa.Text(),
                                             nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meeting_rooms', 'description')
    # ### end Alembic commands ###
